#BSUB -W 3:00
#BSUB -o /rsrch5/scratch/hsr/toumazislab/Sayaka/OvarianCancer/Salpingectomy/log
#BSUB -e /rsrch5/scratch/hsr/toumazislab/Sayaka/OvarianCancer/Salpingectomy/log
#BSUB -cwd /rsrch5/scratch/hsr/toumazislab/Sayaka/OvarianCancer/Salpingectomy
#BSUB -q short
#BSUB -n 40
#BSUB -M 165
#BSUB -R rusage[mem=165]
#BSUB -B
#BSUB -N
#BSUB -u sishizawa@mdanderson.org
#BSUB -J Main_v2

module load julia/1.8.1
julia --threads 40 /rsrch5/scratch/hsr/toumazislab/Sayaka/OvarianCancer/Salpingectomy/main_v2.jl